# Generated by Django 4.2.16 on 2024-11-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_companysettings_employee_attendancerecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Beklemede'), ('approved', 'Onaylı'), ('rejected', 'Reddedildi')], default='pending', max_length=10),
        ),
    ]
